version: 0.2

env:
  shell: /bin/sh
phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Login ECR.
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 968647894618.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t coworking .
      - docker tag coworking:latest 968647894618.dkr.ecr.us-east-1.amazonaws.com/coworking:latest

  build:
    on-failure: ABORT
    commands:
      - docker push 968647894618.dkr.ecr.us-east-1.amazonaws.com/coworking:latest